version: '3.8'

services:
  camera-monitor:
    build: .
    container_name: camera-monitor
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9000-9999:9000-9999"
    volumes:
      - ./data/snapshots:/app/public/snapshots
      - ./data/analytics:/app/public/analytics
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET:-ilovesecurecamera}
      # DeepStack AI settings (uncomment if needed)
      # - DEEPSTACK_HOST=${DEEPSTACK_HOST:-}
      # - DEEPSTACK_PORT=${DEEPSTACK_PORT:-80}
      # - DEEPSTACK_API_KEY=${DEEPSTACK_API_KEY:-}

  # Uncomment sections below to add additional services like DeepStack

  # deepstack:
  #   image: deepquestai/deepstack:latest
  #   container_name: deepstack-ai
  #   restart: unless-stopped
  #   ports:
  #     - "5080:5000"
  #   environment:
  #     - VISION-DETECTION=True
  #     - VISION-FACE=True
  #     - API-KEY=${DEEPSTACK_API_KEY:-}
  #   volumes:
  #     - ./deepstack/models:/modelstore/detection
  #     - ./deepstack/faces:/modelstore/face
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]